dist: xenial
language: python
python: 3.7
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - pytest -vvv

deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: "arrrlo"
  password:
    secure: "_enter_password_here_"
  skip_existing: true
  on:
    branch: master
